// Generated by CoffeeScript 1.8.0
(function() {
  var calculate, get_current_index, populate_menu_tabs, populate_selects;

  populate_menu_tabs = function() {
    var navbar;
    navbar = $('.category_menu');
    $.each(property, function(index, category) {
      return navbar.append("<li index='" + index + "'><a href='#'>" + category + "</a></li>");
    });
    return navbar.find('li[index=7]').addClass('active');
  };

  populate_selects = function() {
    var from_select, to_select;
    from_select = $('select[name=from]');
    to_select = $('select[name=to]');
    from_select.find('option').remove();
    to_select.find('option').remove();
    $.each(unit[get_current_index()], function(i, unit_option) {
      from_select.append("<option>" + unit_option + "</option>");
      return to_select.append("<option>" + unit_option + "</option>");
    });
    return to_select.prop('selectedIndex', 1);
  };

  get_current_index = function() {
    return parseInt($('.category_menu').find('li.active').attr('index'));
  };

  calculate = function() {
    var from_factor, result, selected_from_unit_index, selected_to_unit_index, to_factor;
    selected_from_unit_index = $('select[name=from]').prop('selectedIndex');
    selected_to_unit_index = $('select[name=to]').prop('selectedIndex');
    if ((selected_from_unit_index !== -1) && (selected_to_unit_index !== -1)) {
      from_factor = factor[get_current_index()][selected_from_unit_index];
      to_factor = factor[get_current_index()][selected_to_unit_index];
      result = ($('input[name=how_many_from]').val() * from_factor) / to_factor;
      return $('input[name=how_many_to]').val(result);
    }
  };

  $(function() {
    populate_menu_tabs();
    populate_selects();
    $('input[name=how_many_from]').val('1');
    calculate();
    $('.category_menu a').click(function() {
      $('.category_menu li.active').removeClass('active');
      $(this).parent().addClass('active');
      populate_selects();
      $('input[name=how_many_from]').val('1');
      calculate();
      return false;
    });
    return $('button.go').click(function() {
      return calculate();
    });
  });

}).call(this);
